name: ci

on:
  pull_request:
    branches:
      - main
      - development
  repository_dispatch:
    types: [build, release]


env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: clippy

      - name: Run Clippy
        # uses: actions-rs/clippy-check@v1
        uses: jajuojan/clippy-check@windows-testing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
