name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: windows-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: rust
          package-name: Hello World
